

const testTicket = {
    ITEM: 1,
    TIPO: "INSTALACION CABLE E INTERNET",
    "NUMERO OS": 1,
    ABONADO: 1,
    "ESTADO ABONADO": "ACTIVO",
    NOMBRES: { "RAZON SOCIAL": "OCPO DURAN, ALVARO " },
    "DOC IDENTIDAD": "16613915",
    "SERVICIO INTERNET": "SERVICIO INTERNET",
    DEUDA: "0,00",
    MUNICIPIO: "CUMARAL",
    BARRIO: "FINCA",
    ITEM: 1,
    TIPO: "INSTALACION CABLE E INTERNET",
    "NUMERO OS": 1,
    ABONADO: 1,
    "ESTADO ABONADO": "ACTIVO",
    NOMBRES: { "RAZON SOCIAL": "OCPO DURAN, ALVARO " },
    "DOC IDENTIDAD": "16613915",
    "SERVICIO INTERNET": "SERVICIO INTERNET",
    DEUDA: "0,00",
    MUNICIPIO: "CUMARAL",
    BARRIO: "FINCA",
    DIRECCION: "KILIAWIRINA ",
    DscSector: "GUACAVIA",
    TELEFONO: 3138713550,
    "TARIFA INTERNET2": "20 MB - PLATINO",
    FECHARECEPCION: "09/03/2021",
    HORARECEPCION: "09:05",
    FECHAEJECUCION: "13/03/2021",
    "HOR INICIO": "07:30",
    "HOR FIN": "10:00",
    "NOMBRES VENDEDOR": "OFICINA OFICINA, OFICINA RESERVADO",
    "NOMBRES TECNICO": "GUZMAN JIMENEZ, WILMER EFRAIN",
    OBSERVACIONES: "",
    OBSERVACIONESTECNICO:
      "SE LE INSTALA EL SERVICIO DE INTERNET DEJANDO 236 METROS DE CABLE PARA UN TOTAL DE 366 METROS INSTALADOS SE UTILIZA 4 RRES 2 M.C",
    "DIRECCION (PLANO": {
      SECTOR: { RUTA: { "NROCASA)": "CUMARAL-GUACAVIA-FINCA-KILIAWIRINA " } },
    },
    "REF DIRECCION": "ESTRATO 2",
    "F RECEP.": "09/03/2021",
    HORA: "09:05",
    "F ATENC.": "13/03/2021",
    "ESTADO OS": "DESCARGADA",
    "PERSONA REGISTRO OS": "VIUCHE GUEVARA, ANGIE NATALIA",
    "PERSONA CERRO OS": "GUEVARA TAPIERO, YEIMI ",
    "FECHA CERRO OS": "15/03/2021",
    "HORA CERRO OS": "11:54",
    "MATERIALES UTILIZADOS": "",
    "MATERIALES RECOGIDOS": "",
    POSTE: "",
    "PUNTAJE OS": 0,
    FIELD39: "",//PREGUNTAR A DIANA
    DIRECCION: "KILIAWIRINA ",
    DscSector: "GUACAVIA",
    TELEFONO: 3138713550,
    "TARIFA INTERNET2": "20 MB - PLATINO",
    FECHARECEPCION: "09/03/2021",
    HORARECEPCION: "09:05",
    FECHAEJECUCION: "13/03/2021",
    "HOR INICIO": "07:30",
    "HOR FIN": "10:00",
    "NOMBRES VENDEDOR": "OFICINA OFICINA, OFICINA RESERVADO",
    "NOMBRES TECNICO": "GUZMAN JIMENEZ, WILMER EFRAIN",
    OBSERVACIONES: "",
    OBSERVACIONESTECNICO:
      "SE LE INSTALA EL SERVICIO DE INTERNET DEJANDO 236 METROS DE CABLE PARA UN TOTAL DE 366 METROS INSTALADOS SE UTILIZA 4 RRES 2 M.C",
    "DIRECCION (PLANO": {
      SECTOR: { RUTA: { "NROCASA)": "CUMARAL-GUACAVIA-FINCA-KILIAWIRINA " } },
    },
    "REF DIRECCION": "ESTRATO 2",
    "F RECEP.": "09/03/2021",
    HORA: "09:05",
    "F ATENC.": "13/03/2021",
    "ESTADO OS": "DESCARGADA",
    "PERSONA REGISTRO OS": "VIUCHE GUEVARA, ANGIE NATALIA",
    "PERSONA CERRO OS": "GUEVARA TAPIERO, YEIMI ",
    "FECHA CERRO OS": "15/03/2021",
    "HORA CERRO OS": "11:54",
    "MATERIALES UTILIZADOS": "",
    "MATERIALES RECOGIDOS": "",
    POSTE: "",
    "PUNTAJE OS": 0,
    FIELD39: "",
  }

const dateStringTest = `${testTicket["FECHA CERRO OS"]} ${testTicket["HORA CERRO OS"]}`

console.log(dateStringTest)


const dateString = '12/03/2021 17:45'

const parsedDate = Date.parse(dateStringTest)

const dateObject = new Date(parsedDate)

console.log(dateObject)
