export const SIGNIN_USER = 'SIGNIN_USER';
export const LOGOUT_USER = 'LOGOUT_USER';
export const GET_USERS = "GET_USERS";
export const CLEAN_DETAIL = 'CLEAN_DETAIL';
export const FETCH_USER_CONTRACTS_REQUEST = 'FETCH_USER_CONTRACTS_REQUEST';
export const FETCH_USER_CONTRACTS_SUCCESS = 'FETCH_USER_CONTRACTS_SUCCESS';
export const FETCH_USER_CONTRACTS_FAILURE = 'FETCH_USER_CONTRACTS_FAILURE';
export const FETCH_CONTRACT_DETAILS_REQUEST = 'FETCH_CONTRACT_DETAILS_REQUEST';
export const FETCH_CONTRACT_DETAILS_SUCCESS = 'FETCH_CONTRACT_DETAILS_SUCCESS';
export const FETCH_CONTRACT_DETAILS_FAILURE = 'FETCH_CONTRACT_DETAILS_FAILURE';
export const CLEAN_CONTRACT_DETAILS = 'CLEAN_CONTRACT_DETAILS';
export const CLEAN_USER_CONTRACTS = 'CLEAN_USER_CONTRACTS';
export const SHOW_NO_CONTRACTS_MODAL = 'SHOW_NO_CONTRACTS_MODAL';
export const CLOSE_MODAL = 'CLOSE_MODAL';
export const CREATE_CONTRACT_REQUEST = 'CREATE_CONTRACT_REQUEST';
export const CREATE_CONTRACT_SUCCESS = 'CREATE_CONTRACT_SUCCESS';
export const CREATE_CONTRACT_FAILURE = 'CREATE_CONTRACT_FAILURE';
export const SAVE_FINGERPRINT = 'SAVE_FINGERPRINT';


