export const SIGNIN_USER = 'SIGNIN_USER';
export const LOGOUT_USER = 'LOGOUT_USER';
export const GET_USERS = "GET_USERS";
export const CLEAN_DETAIL = 'CLEAN_DETAIL';
export const CREATE_USER = "CREATE_USER";
export const FETCH_ASSIGNED_TASKS_REQUEST = 'FETCH_ASSIGNED_TASKS_REQUEST';
export const FETCH_ASSIGNED_TASKS_SUCCESS = 'FETCH_ASSIGNED_TASKS_SUCCESS';
export const FETCH_ASSIGNED_TASKS_FAILURE = 'FETCH_ASSIGNED_TASKS_FAILURE';
export const ASSIGN_TASK_TO_USER_REQUEST = 'ASSIGN_TASK_TO_USER_REQUEST';
export const ASSIGN_TASK_TO_USER_SUCCESS = 'ASSIGN_TASK_TO_USER_SUCCESS';
export const ASSIGN_TASK_TO_USER_FAILURE = 'ASSIGN_TASK_TO_USER_FAILURE';




